AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*

SpecialGlobalVars:
  Enabled: false

AsciiComments:
  Enabled: false

ClassLength:
  Max: 200

Documentation:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Max: 30

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

